const Question = require("../models/Question");

const { getOrgsNamesByType } = require("../queries/review");

/**
 * questions types:
 * 1.open: accept any string
 * 2.yesno: yes or no
 * 3.radio: one of many choices
 * 4.number: accpet only number as an answer (hourlyrate)
 * 5.checklist: to choose more than one option
 * 6.image: for questions the require uploading images
 */

const organization = {
  types: {
    1: "yesno",
    2: "dropdown",
    3: "open",
    4: "number",
    5: "image",
    6: "checklist",
  },
  category: {
    1: "agency",
    2: "payroll",
    3: "worksite",
    4: "company",
  },
};

module.exports = async () => {
  let agencyNames;
  let payrollsNames;
  try {
    const agencies = await getOrgsNamesByType("agency");
    const payrolls = await getOrgsNamesByType("payroll");

    agencyNames = agencies[0].category;
    payrollsNames = payrolls[0].category;
  } catch (err) {
    console.log("database query error", err);
  }

  const questions = [
    {
      number: 1,
      type: "yesno",
      text: "Did they send you written confirmation of the terms and conditions of employment?",
      hintText:
        "i.e., details of pay, overtime, mileage/travel allowance, lodging provision, holiday entitlement, disciplinary procedures, benefits, etc.",
      isJumping: true,
      jumpTo: [{ value: "yes", nextQuestion: 2 }, { value: "no", nextQuestion: 3 }],
      options: ["yes", "no"],
      category: "agency",
      profileText: "Sends you written confirmation of terms and conditions of employment",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 2,
      type: "yesno",
      text: "Did they send you this information before your work began?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Sends you terms and conditions before your work begins",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 3,
      type: "radio",
      text:
        "Taking into account all the information you were given before starting work, such as pay, hours, type of work and length of job, how accurate was the description you were given about the job overall?",
      isJumping: false,
      options: ["totally inaccurate", "Not very accurate", "Mostly accurate", "Fully accurate"],
      category: "agency",
      profileText: "Accuracy of job descriptions given to you overall",
      profileSection: "Detailed ratings",
      profileType: "pieChart",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 4,
      type: "yesno",
      text: "Did they give you correct information about the pay?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Gives you correct information about the pay",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 5,
      type: "yesno",
      text: "Did they give you correct information about the hours?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Gives you correct information about the hours",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 6,
      type: "yesno",
      text: "Did they give you correct information about the type of work?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Gives you correct information about the type of work",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 7,
      type: "yesno",
      text: "Did they give you correct information about the length of the job?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Gives you correct information about the length of the job",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 9,
      type: "number",
      text: "What hourly rate were you paid?",
      label: "per hour",
      isJumping: false,
      category: "agency",
      profileText: "Hourly pay rates over time",
      profileSection: "Detailed ratings",
      profileType: "dotChart",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 10,
      type: "yesno",
      text: "Were you paid via a payroll/umbrella?",
      isJumping: true,
      jumpTo: [{ value: "yes", nextQuestion: 18 }, { value: "no", nextQuestion: 11 }],
      options: ["yes", "no"],
      category: "agency",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 11,
      type: "dropdown",
      text: "What's the name of the payroll?",
      label: "Select payroll",
      isJumping: false,
      options: payrollsNames,
      category: "agency",
      profileText: "Pays using the following payrolls",
      profileSection: "Key ratings",
      profileType: "payrollList",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: false,
    },
    {
      number: 12,
      type: "yesno",
      text: "What was the payroll type?",
      isJumping: false,
      options: ["CIS", "Ltd", "PAYE", "Umbrella"],
      category: "agency",
      profileText: "Pays using the following payroll types",
      profileSection: "Key ratings",
      profileType: "barChart",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: false,
    },
    {
      number: 13,
      type: "yesno",
      text: "Were you paid within the timeframe you expected?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Pays you within the timeframe you expect",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 14,
      type: "yesno",
      text: "Were you paid the amount you expected?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Pays you the amount you expect",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 15,
      type: "yesno",
      text: "Were your payslips easily accessible?",
      isJumping: false,
      options: ["yes", "no", "I didn't check"],
      category: "agency",
      profileText: "Payslips are easily accessible",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 16,
      type: "yesno",
      text: "Did the payslips show all the information you needed?",
      isJumping: false,
      options: ["yes", "no", "I didn't check"],
      category: "agency",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 17,
      type: "yesno",
      text: "Were you charged for payroll?",
      isJumping: true,
      jumpTo: [{ value: "yes", nextQuestion: 17 }, { value: "no", nextQuestion: 18 }],
      options: ["yes", "no"],
      category: "agency",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 18,
      type: "number",
      text: "How much were you charged?",
      label: "per timesheet",
      isJumping: false,
      category: "agency",
      profileType: "payrollSubList",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 19,
      type: "yesno",
      text: "Were you always treated fairly by this agency over any payment issues?",
      isJumping: false,
      options: ["yes", "no", "no issues"],
      category: "agency",
      profileText: "Treated fairly by this agency over any payment issues",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting your wages",
      },
      hasComment: true,
    },
    {
      number: 20,
      type: "yesno",
      text: "Overall, would you be happy to use this agency again?",
      isJumping: false,
      options: ["yes", "no"],
      category: "agency",
      profileText: "Happy to use this agency again overall",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 2,
        name: "overall",
        text: "Overall rating",
      },
      hasComment: true,
    },

    /* =========================== questionsPayroll ==================================== */

    {
      number: 1,
      type: "yesno",
      text: "Did they send you written confirmation of the terms and conditions of employment?",
      hintText:
        "i.e., details of pay, overtime, mileage/travel allowance, lodging provision, holiday entitlement, disciplinary procedures, benefits, etc.",
      isJumping: true,
      jumpTo: [{ value: "yes", nextQuestion: 2 }, { value: "no", nextQuestion: 3 }],
      options: ["yes", "no"],
      category: "payroll",
      profileText: "Sends you written confirmation of terms and conditions of employment",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 2,
      type: "yesno",
      text: "Did they send you this information before your work began?",
      isJumping: false,
      options: ["yes", "no"],
      category: "payroll",
      profileText: "Sends you terms and conditions before your work begins",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "general",
        text: "General",
      },
      hasComment: true,
    },
    {
      number: 4,
      type: "number",
      text: "What hourly rate were you paid?",
      label: "per hour",
      isJumping: false,
      category: "payroll",
      profileText: "Hourly pay rates over time",
      profileSection: "Detailed ratings",
      profileType: "dotChart",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 5,
      type: "radio",
      text: "What was the payroll type?",
      isJumping: false,
      options: ["CIS", "Ltd", "PAYE", "Umbrella"],
      category: "payroll",
      profileText: "Pays using the following payroll types",
      profileSection: "Key ratings",
      profileType: "barChart",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: false,
    },
    {
      number: 6,
      type: "yesno",
      text: "Were you paid within the timeframe you expected?",
      isJumping: false,
      options: ["yes", "no"],
      category: "payroll",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 7,
      type: "yesno",
      text: "Were you paid the amount you expected?",
      isJumping: false,
      options: ["yes", "no"],
      category: "payroll",
      profileText: "Pays you within the timeframe you expect",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 8,
      type: "radio",
      text: "Were your payslips easily accessible?",
      isJumping: false,
      options: ["yes", "no", "I didn't check"],
      category: "payroll",
      profileText: "Payslips are easily accessible",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 9,
      type: "radio",
      text: "Did the payslips show all the information you needed?",
      isJumping: false,
      options: ["yes", "no", "I didn't check"],
      category: "payroll",
      profileText: "Payslips show all the information you need",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 10,
      type: "yesno",
      text: "Were you charged for payroll?",
      isJumping: true,
      jumpTo: [{ value: "yes", nextQuestion: 11 }, { value: "no", nextQuestion: 12 }],
      options: ["yes", "no"],
      category: "payroll",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 11,
      type: "number",
      text: "How much were you charged?",
      label: "per timesheet",
      isJumping: false,
      category: "payroll",
      profileText: "Payroll charge",
      profileSection: "Key ratings",
      profileType: "list",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 12,
      type: "radio",
      text: "Were you always treated fairly by this payroll over any payment issues?",
      isJumping: false,
      options: ["yes", "no", "no issues"],
      category: "payroll",
      profileText: "Treats you fairly over any payment issues",
      profileSection: "Detailed ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: true,
    },
    {
      number: 13,
      type: "dropdown",
      text: "What's the name of the agency you used?",
      label: "Select agency",
      isJumping: false,
      options: agencyNames,
      category: "payroll",
      profileText: "Works with the following agencies",
      profileSection: "Key ratings",
      profileType: "list",
      group: {
        groupOrder: 1,
        name: "wages",
        text: "Getting yor wages",
      },
      hasComment: false,
    },

    {
      number: 14,
      type: "yesno",
      text: "Overall, would you be happy to use this payroll again?",
      isJumping: false,
      options: ["yes", "no"],
      category: "payroll",
      profileText: "Happy to use this payroll again overall",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 2,
        name: "overall",
        text: "Overall rating",
      },
      hasComment: true,
    },

    /* =============================== worksite ================================ */
    {
      number: 1,
      type: "radio",
      text: "Was there public transport within 10 minutes walk of site?",
      hintText: "i.e., buses, trains, etc.",
      isJumping: false,
      options: ["yes", "no", "don't know"],
      category: "worksite",
      profileText: "Public transport within 10 mins walk of site",
      profileSection: "Getting onto site",
      profileType: "siteItem",
      group: {
        groupOrder: 0,
        name: "getToSite",
        text: "Getting on to site",
      },
      hasComment: true,
    },
    {
      number: 2,
      type: "radio",
      text: "Was there car parking within 10 minutes walk of site?",
      isJumping: true,
      jumpTo: [
        { value: "yes", nextQuestion: 3 },
        { value: "no", nextQuestion: 5 },
        { value: "don't know", nextQuestion: 5 },
      ],
      options: ["yes", "no", "don't know"],
      category: "worksite",
      profileText: "Car parking within 10 mins walk of site",
      profileSection: "Getting onto site",
      profileType: "siteItem",
      group: {
        groupOrder: 0,
        name: "getToSite",
        text: "Getting on to site",
      },
      hasComment: true,
    },
    {
      number: 3,
      type: "yesno",
      text: "Was the car parking free?",
      isJumping: true,
      jumpTo: [{ value: "yes", nextQuestion: 5 }, { value: "no", nextQuestion: 4 }],
      options: ["yes", "no"],
      category: "worksite",
      group: {
        groupOrder: 0,
        name: "getToSite",
        text: "Getting on to site",
      },
      hasComment: true,
    },
    {
      number: 4,
      type: "number",
      text: "How much did car parking cost per day?",
      label: "per day",
      isJumping: false,
      category: "worksite",
      group: {
        groupOrder: 0,
        name: "getToSite",
        text: "Getting on to site",
      },
      hasComment: true,
    },
    {
      number: 5,
      type: "radio",
      text: "At the site, were you offered secure storage for your personal belongings?",
      hintText: "E.g., Lockers, cloak room, etc.",
      isJumping: false,
      options: ["yes", "no", "yes, but I didn't need it"],
      category: "worksite",
      profileText: "Secure storage for your personal belongings",
      profileSection: "Getting onto site",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "getToSite",
        text: "Getting on to site",
      },
      hasComment: true,
    },

    {
      number: 6,
      type: "yesno",
      text: "Did you have to use fingerprint scanners or eye recognition to access the site?",
      isJumping: false,
      options: ["yes", "no"],
      category: "worksite",
      profileText: "Fingerprint scanners/eye-recognition to access site",
      profileSection: "Getting onto site",
      profileType: "siteItem",
      group: {
        groupOrder: 0,
        name: "getToSite",
        text: "Getting on to site",
      },
      hasComment: true,
    },

    {
      number: 7,
      type: "yesno",
      text: "Were the work areas tidy?",
      isJumping: false,
      options: ["yes", "no"],
      category: "worksite",
      profileText: "Work areas are tidy",
      profileSection: "Working on the site",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "onTheSite",
        text: "Working on the site",
      },
      hasComment: true,
    },

    {
      number: 8,
      type: "yesno",
      text: "Did you feel this site was safe to work on?",
      isJumping: false,
      options: ["yes", "no"],
      category: "worksite",
      profileText: "Site is safe to work on",
      profileSection: "Working on the site",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "onTheSite",
        text: "Working on the site",
      },
      hasComment: true,
    },

    {
      type: "image",
      text: "Upload a photo of the site",
      hintText:
        "Offer workers a behind-the-scenes look at the site, e.g., work areas, canteen, etc.",
      isJumping: false,
      category: "worksite",
      profileText: "Site images",
      profileSection: "Working on the site",
      group: {
        groupOrder: 1,
        name: "onTheSite",
        text: "Working on the site",
      },
      hasComment: false,
    },
    {
      number: 9,
      type: "yesno",
      text: "Were the toilets well maintained?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileText: "Toilets are well maintained",
      profileSection: "The site welfare",
      profileType: "yesno",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 10,
      type: "yesno",
      text: "Was there free drinking water available?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileText: "Free drinking water",
      profileSection: "The site welfare",
      profileType: "siteItem",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 11,
      type: "yesno",
      text: "Did this site have a prayer room?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileText: "Prayer room",
      profileSection: "The site welfare",
      profileType: "siteItem",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 12,
      type: "radio",
      text: "Was there a canteen or space to take a break?",
      isJumping: true,
      jumpTo: [
        { value: "yes", nextQuestion: 14 },
        { value: "no", nextQuestion: 16 },
        { value: "don't know", nextQuestion: 16 },
      ],
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileText: "Canteen:",
      profileSection: "The site welfare",
      profileType: "canteenItem",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 13,
      type: "radio",
      text: "Was the canteen heated?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileSection: "The site welfare",
      profileType: "canteenItem",
      profileText: "heated",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 14,
      type: "checklist",
      text: "What amenities did the canteen have?",
      isJumping: false,
      options: [
        "hot foot served",
        "vending machines",
        "tables and charis",
        "microwave",
        "kettle/boiling water",
        "fridge",
        "I didn't check",
      ],
      category: "worksite",
      profileSection: "The site welfare",
      profileType: "canteenItem",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 15,
      type: "radio",
      text: "Were there shops to buy hot food within 10 minutes walk of this site?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileText: "Shops for hot food within 10 mins walk of site",
      profileSection: "The site welfare",
      profileType: "siteItem",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 16,
      type: "radio",
      text: "Could you buy hot food and a drink for less than £5?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "worksite",
      profileText: "Can buy hot food and a drink for less than £5",
      profileSection: "The site welfare",
      profileType: "siteItem",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 17,
      type: "open",
      text: "Is there a good shop or café near site that you would recommend to other workers?",
      label: "Good shop or café",
      isJumping: false,
      category: "worksite",
      profileText: "Recommended nearby shops and cafés",
      profileSection: "The site welfare",
      profileType: "list",
      group: {
        groupOrder: 2,
        name: "siteWelfare",
        text: "The site welfare",
      },
      hasComment: true,
    },
    {
      number: 18,
      type: "yesno",
      text: "Overall, would you be happy to work on this site again?",
      isJumping: false,
      options: ["yes", "no"],
      category: "worksite",
      profileText: "Happy to work on this site again overall",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 3,
        name: "overall",
        text: "Overall rating",
      },
      hasComment: true,
    },

    /* ============================= company ================================== */

    {
      number: 1,
      type: "yesno",
      text: "Was their materials store well organised?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "company",
      profileText: "Materials stores are well organised",
      profileSection: "Tools & materials",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "toolsAndMaterials",
        text: "Tools & materials",
      },
      hasComment: true,
    },
    {
      number: 2,
      type: "yesno",
      text: "Were you offered access equipment when you needed it?",
      hintText: "E.g., stepladders, harnesses, lifters, etc.",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "company",
      profileText: "Offers access equipment when you need it",
      profileSection: "Tools & materials",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "toolsAndMaterials",
        text: "Tools & materials",
      },
      hasComment: true,
    },
    {
      number: 3,
      type: "radio",
      text: "Was the access equipment in safe condition?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "company",
      profileText: "Access equipment is in safe condition",
      profileSection: "Tools & materials",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "toolsAndMaterials",
        text: "Tools & materials",
      },
      hasComment: true,
    },
    {
      number: 4,
      type: "radio",
      text: "Were you offered secure storage for your tools overnight?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "company",
      profileText: "Offers secure storage for your tools overnight when you need it",
      profileSection: "Tools & materials",
      profileType: "yesno",
      group: {
        groupOrder: 0,
        name: "toolsAndMaterials",
        text: "Tools & materials",
      },
      hasComment: true,
    },
    {
      number: 5,
      type: "yesno",
      text: "Did the supervisor share all the information you needed to do a good job?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "company",
      profileText: "Supervisors share all the information you need to do a good job",
      profileSection: "Supervisors & employees",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "supervisorsAndEmployees",
        text: "Supervisors & employees",
      },
      hasComment: true,
    },
    {
      number: 6,
      type: "yesno",
      text: "Did the supervisor treat you with respect?",
      isJumping: false,
      options: ["yes", "no", "i didn't check"],
      category: "company",
      profileText: "Supervisors treat you with respect",
      profileSection: "Supervisors & employees",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "supervisorsAndEmployees",
        text: "Supervisors & employees",
      },
      hasComment: true,
    },
    {
      number: 8,
      type: "yesno",
      text: "Did the other company employees treat you with respect?",
      isJumping: false,
      options: ["yes", "no"],
      category: "company",
      profileText: "Employees treat you with respect",
      profileSection: "Supervisors & employees",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "supervisorsAndEmployees",
        text: "Supervisors & employees",
      },
      hasComment: true,
    },
    {
      number: 9,
      type: "yesno",
      text: "Overall, did you feel valued working with this company?",
      isJumping: false,
      options: ["yes", "no"],
      category: "company",
      profileText: "Feel valued working with this company overall",
      profileSection: "Supervisors & employees",
      profileType: "yesno",
    },
    {
      number: 10,
      type: "yesno",
      text: "Overall, would you be happy to work for this company again?",
      isJumping: false,
      options: ["yes", "no"],
      category: "company",
      profileText: "Happy to work for this company again overall",
      profileSection: "Key ratings",
      profileType: "yesno",
      group: {
        groupOrder: 1,
        name: "supervisorsAndEmployees",
        text: "Supervisors & employees",
      },
      hasComment: true,
    },
    {
      number: 10,
      type: "yesno",
      text: "Overall, would you be happy to work with this company again?",
      isJumping: false,
      options: ["yes", "no"],
      category: "company",
      group: {
        groupOrder: 2,
        name: "`overall`",
        text: "Overall rating",
      },
      hasComment: true,
    },
  ];
  return Question.create(questions);
};
