const { Schema } = require("mongoose");


/**
 * questions types:
 * 1.open: accept any string
 * 2.yesno: yes or no
 * 3.radio: one of many choices
 * 4.number: accpet only number as an answer (hourlyrate)
 * 5.checklist: to choose more than one option
 * 6.image: for questions the require uploading images
 */
const questions = [
  {
    id: Schema.Types.ObjectId,
    number: 1,
    type: "yesno",
    text: "Did they send you written confirmation of the terms and conditions of employment?",
    hintText: "i.e., details of pay, overtime, mileage/travel allowance, lodging provision, holiday entitlement, disciplinary procedures, benefits, etc.",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 2 }, { value: "no", nextQuestion: 3 }],
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 2,
    type: "yesno",
    text: "Did they send you this information before your work began?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 3,
    type: "radio",
    text: "Taking into account all the information you were given before starting work, such as pay, hours, type of work and length of job, how accurate was the description you were given about the job overall?",
    isJumping: false,
    options: ["totally inaccurate", "Not very accurate", "Mostly accurate", "Fully accurate"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 4,
    type: "yesno",
    text: "Did they give you correct information about the pay?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 5,
    type: "yesno",
    text: "Did they give you correct information about the hours?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 6,
    type: "yesno",
    text: "Did they give you correct information about the type of work?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 7,
    type: "yesno",
    text: "Did they give you correct information about the length of the job?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 8,
    type: "open",
    text: "What's the name of the rep you dealt with at this agency?",
    hintText: "This will be seen only by the agency",
    isJumping: false,
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 9,
    type: "number",
    text: "What hourly rate were you paid?",
    isJumping: false,
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 10,
    type: "yesno",
    text: "Were you paid via a payroll/umbrella?",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 18 }, { value: "no", nextQuestion: 11 }],
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 11,
    type: "radio",
    text: "What's the name of the payroll?",
    isJumping: false,
    options: [
      "Capital Payroll Services",
      "Champion Contractors",
      "Churchill Knight",
      "Cinch",
      "Credipay",
      "Crunch",
      "Crystal Choice",
      "Crystal Payroll (Payroll Services Company)",
      "Danbro",
    ],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 12,
    type: "radio",
    text: "What was the payroll type?",
    isJumping: false,
    options: ["CIS", "Ltd", "PAYE", "Umbrella"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 13,
    type: "yesno",
    text: "Were you paid within the timeframe you expected?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 14,
    type: "yesno",
    text: "Were you paid the amount you expected?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 15,
    type: "radio",
    text: "Were your payslips easily accessible?",
    isJumping: false,
    options: ["yes", "no", "I didn't check"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 16,
    type: "yesno",
    text: "Were you charged for payroll?",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 17 }, { value: "no", nextQuestion: 18 }],
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 17,
    type: "number",
    text: "How much were you charged?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 18,
    type: "radio",
    text: "Were you always treated fairly by this agency over any payment issues?",
    isJumping: false,
    options: ["yes", "no", "no issues"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 19,
    type: "yesno",
    text: "Overall, would you be happy to use this agency again?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },

  /* =========================== questionsPayroll ==================================== */

  {
    id: Schema.Types.ObjectId,
    number: 1,
    type: "yesno",
    text: "Did they send you written confirmation of the terms and conditions of employment?",
    hintText: "i.e., details of pay, overtime, mileage/travel allowance, lodging provision, holiday entitlement, disciplinary procedures, benefits, etc.",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 2 }, { value: "no", nextQuestion: 3 }],
    options: ["yes", "no"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 2,
    type: "yesno",
    text: "Did they send you this information before your work began?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 3,
    type: "radio",
    text: "What’s the name of the rep you dealt with at this payroll?",
    hintText: "This will be seen only by the payroll",
    isJumping: false,
    options: ["totally inaccurate", "Not very accurate", "Mostly accurate", "Fully accurate"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 4,
    type: "number",
    text: "What hourly rate were you paid?",
    isJumping: false,
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 5,
    type: "radio",
    text: "What was the payroll type?",
    isJumping: false,
    options: ["CIS", "Ltd", "PAYE", "Umbrella"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 6,
    type: "yesno",
    text: "Were you paid within the timeframe you expected?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 7,
    type: "yesno",
    text: "Were you paid the amount you expected?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 8,
    type: "radio",
    text: "Were your payslips easily accessible?",
    isJumping: false,
    options: ["yes", "no", "I didn't check"],
    orgType: "Agency",
  },
  {
    id: Schema.Types.ObjectId,
    number: 9,
    type: "radio",
    text: "Did the payslips show all the information you needed?",
    isJumping: false,
    options: ["yes", "no", "I didn't check"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 10,
    type: "yesno",
    text: "Were you charged for payroll?",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 11 }, { value: "no", nextQuestion: 12 }],
    options: ["yes", "no"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 11,
    type: "number",
    text: "How much were you charged?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 12,
    type: "radio",
    text: "Were you always treated fairly by this payroll over any payment issues?",
    isJumping: false,
    options: ["yes", "no", "no issues"],
    orgType: "payroll",
  },
  {
    id: Schema.Types.ObjectId,
    number: 13,
    type: "radio",
    text: "What's the name of the agency you used?",
    isJumping: false,
    options: [
      "Acrow Recruitment",
      "Adecco",
      "Advanced Technical Recruitment",
      "Ahearne Support Services (previously: Gulmanda)",
      "Anderselite",
      "Apex Recruitment",
      "Approach Personnel Specialists",
      "Artisan",
      "Aspire Recruitment",
      "Atlas Recruitment Group",
      "Aztec Resources",
      "B M S L",
      "B M S Performance",
      "Bally Common",
      "Besboke Civils Solutions (B C S)",
      "Blade Recruitment",
      "Bluebaring Recruitment",
      "Bluebell",
    ],
    orgType: "payroll",
  },

  {
    id: Schema.Types.ObjectId,
    number: 14,
    type: "yesno",
    text: "Overall, would you be happy to use this agency again?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "payroll",
  },

  /* =============================== worksite ================================ */

  {
    id: Schema.Types.ObjectId,
    number: 1,
    type: "radio",
    text: "Was there public transport within 10 minutes walk of site?",
    hintText: "i.e., buses, trains, etc.",
    isJumping: false,
    options: ["yes", "no", "don't know"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 2,
    type: "radio",
    text: "Was there car parking within 10 minutes walk of site?",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 3 }, { value: "no", nextQuestion: 5 }, { value: "don't know", nextQuestion: 5 }],
    options: ["yes", "no", "don't know"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 3,
    type: "yesno",
    text: "Was the car parking free?",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 5 }, { value: "no", nextQuestion: 4 }],
    options: ["yes", "no"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 4,
    type: "number",
    text: "How much did car parking cost per day?",
    isJumping: false,
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 5,
    type: "number",
    text: "At the site, were you offered secure storage for your personal belongings?",
    hintText: "E.g., Lockers, cloak room, etc.",
    isJumping: false,
    options: ["yes", "no", "yes, but I didn't need it"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 6,
    type: "yesno",
    text: "Did you have to use fingerprint scanners or eye recognition to access the site?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 7,
    type: "yesno",
    text: "Were the work areas tidy?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 8,
    type: "yesno",
    text: "Did you feel this site was safe to work on?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 9,
    type: "image",
    text: "Upload a photo of the site",
    hintText: "Offer workers a behind-the-scenes look at the site, e.g., work areas, canteen, etc.",
    isJumping: false,
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 10,
    type: "radio",
    text: "Were the toilets well maintained?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 11,
    type: "radio",
    text: "Was there free drinking water available?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 12,
    type: "radio",
    text: "Did this site have a prayer room?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 13,
    type: "radio",
    text: "Was there a canteen or space to take a break?",
    isJumping: true,
    jumpTo: [{ value: "yes", nextQuestion: 14 }, { value: "no", nextQuestion: 16 }, { value: "don't know", nextQuestion: 16 }],
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 14,
    type: "radio",
    text: "Was the canteen heated?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 15,
    type: "checklist",
    text: "What amenities did the canteen have?",
    isJumping: false,
    options: ["hot foot served", "vending machines", "tables and charis", "microwave", "kettle/boiling water", "fridge", "I didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 16,
    type: "radio",
    text: "Were there shops to buy hot food within 10 minutes walk of this site?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 17,
    type: "radio",
    text: "Could you buy hot food and a drink for less than £5?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 18,
    type: "open",
    text: "Is there a good shop or café near site that you would recommend to other workers?",
    isJumping: false,
    orgType: "worksite",
  },
  {
    id: Schema.Types.ObjectId,
    number: 19,
    type: "open",
    text: "Overall, would you be happy to work on this site again?",
    isJumping: false,
    orgType: "worksite",
  },

  /* ============================= company ================================== */

  {
    id: Schema.Types.ObjectId,
    number: 1,
    type: "radio",
    text: "Was their materials store well organised?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 2,
    type: "radio",
    text: "Were you offered access equipment when you needed it?",
    hintText: "E.g., stepladders, harnesses, lifters, etc.",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 3,
    type: "radio",
    text: "Was the access equipment in safe condition?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 4,
    type: "radio",
    text: "Were you offered secure storage for your tools overnight?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 5,
    type: "yesno",
    text: "Did the supervisor share all the information you needed to do a good job?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 6,
    type: "yesno",
    text: "Did the supervisor treat you with respect?",
    isJumping: false,
    options: ["yes", "no", "i didn't check"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 7,
    type: "open",
    text: "What's the name of the supervisor you worked with?",
    hintText: "This will be seen only by the company",
    isJumping: false,
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 8,
    type: "yesno",
    text: "Did the other company employees treat you with respect?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 9,
    type: "yesno",
    text: "Overall, did you feel valued working with this company?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "company",
  },
  {
    id: Schema.Types.ObjectId,
    number: 9,
    type: "yesno",
    text: "Overall, would you be happy to work with this company again?",
    isJumping: false,
    options: ["yes", "no"],
    orgType: "company",
  },
];
